site_name: 2024.1 - SENTINELA
site_url: "https://documentacao-SENTINELA.com/"

repo_name: "2024.1 - SENTINELA"
repo_url: "https://github.com/fga-eps-mds/2024.1-SENTINELA-DOC"

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
        primary: brown

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
        primary: brown

  # logo:
  # favicon:

plugins:
  - search

nav:
  - Sobre: index.md
  - Gestão:
      - Riscos: gestao/riscos.md
      - Arquitetura: gestao/arquitetura.md
      - EAP: gestao/eap.md
      - Metodologia: gestao/metodologia.md
      - Custo: gestao/custo.md
      - Guia de contribuição: gestao/guia-de-contribuicao.md
  - Alinhamento da equipe:
      - Quadro de disponibilidade: alinhamento/disponibilidade.md
      - Quadro de conhecimento: alinhamento/heatmap.md
      - Planejamento de dojos: alinhamento/dojos.md
      - Canais de comunicação: alinhamento/canais.md
  - Lean Inception:
      - Dia 1: lean/dia1.md
      - Dia 2: lean/dia2.md
      - Dia 3: lean/dia3.md
      - Dia 4: lean/dia4.md
      - Dia 5: lean/dia5.md
      - Dia 6: lean/dia6.md
      - Dia 7: lean/dia7.md
  - Sprints:
      - Início:
          - Retomada às atividades: ritos/sprints/inicio/retomada_inicio.md
          - Retrospectiva: ritos/sprints/inicio/retrospec_inicio.md
      - Sprint 1:
          - Planning: ritos/sprints/sprint1/planning1.md
          - Pareamentos: ritos/sprints/sprint1/pareamentos1.md
      - Sprint 2:
          - Planning: ritos/sprints/sprint2/reviewplanning2.md
          - Pareamentos: ritos/sprints/sprint2/pareamentos2.md
      - Sprint 3:
          - Planning: ritos/sprints/sprint3/reviewplanning3.md
          - Pareamentos: ritos/sprints/sprint3/pareamentos3.md
      - Sprint 4:
          - Planning: ritos/sprints/sprint4/reviewplanning4.md
          - Pareamentos: ritos/sprints/sprint4/pareamentos4.md
      - Sprint 5:
          - Planning: ritos/sprints/sprint5/reviewplanning5.md
          - Pareamentos: ritos/sprints/sprint5/pareamentos5.md

  - Prototipagem:
      - Identidade Visual: prototipagem/idv.md
      - Testes de usabilidade: prototipagem/testesusabilidade.md
